name: Run Unit Testing

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - 'feat/**'    
      - 'fix/**'
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"] # can specify list of python versions to use

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          npm install -g aws-cdk
          npm update
          python3 -m pip install --upgrade pip
          if [ -f requirements.txt ]; then python3 -m pip install -r requirements.txt; fi
      - name: Run Unit Testing
        run: |
          python3 -m pytest lambda/Functions_Test/*/test_*.py --capture=sys --cov=lambda/Functions --cov-fail-under=80 --cov-report=term-missing
      - name: Run CDK script
        run: |
          cdk synth